analysis_config:
  enable_risk_analysis: true
  enable_sensitivity_analysis: true
  enable_stability_analysis: true
backtest_config:
  initial_amount: 100000
  stock_pool:
  - 688585
  - 300539
  - 300885
  - 300486
  - 002097
  - 301038
  - 603280
  - 688110
  - 002837
  - 300706
  - 603757
  - 002536
  - 600513
  - 603367
  - 300158
  - 688098
  - 688108
  - 300502
  - 600410
  - 688256
  - 601138
  - 601606
  - 301357
  - 002046
  - 836942
  - 301217
  - 002017
  - 600749
  - 301076
  stock_pool_inline: 300033,300059,000062
  time_range:
    end_date: '2025-08-22'
    start_date: '2024-01-01'
description: 自动生成的BreakoutStrategy网格搜索配置
experiment_name: breakoutstrategy_grid_search
output_config:
  generate_charts: false
  generate_excel_report: false
  generate_markdown_report: true
parameter_sets:
  grid_search:
    consolidation_lookback:
    - 4
    - 5
    - 6
    consolidation_ma_max_slope:
    - 0.95
    - 1.05
    - 1.16
    - 1.26
    consolidation_ma_proximity_pct:
    - 0.02
    - 0.03
parameter_strategy:
  max_combinations: 100
  type: grid_search
